name: gss-saude
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas>=2.1.3
  - openpyxl=3.1.2
  - xlsxwriter=3.1.9
  - beautifulsoup4>=4.12.0
  - requests>=2.31.0
  - pip
  - pip:
      - streamlit>=1.28.0
      - selenium>=4.15.0
      - webdriver-manager>=4.0.1
      - python-dotenv>=1.0.0
